### ISSUE TITLE
not working anymore in Grav 1.0.7

### ISSUE THREAD

**Issue by axel-rank** [Sommerregen/grav-plugin-external-links#10]
Link Icons are not showing up anymore. Same in Grav 1.0.8
Icons are not shown, when the (html) link is in page header. But that was working before.
Link icons in markdown works.

**Comment by Sommerregen** [comment]
Hi @axel-rank ,

I don't know what you mean by

> Icons are not shown, when the (html) link is in page header.

Can you clarify your statement and give an example. To be clear, **External Links** only render links in the page content to be external (when they are) not any links in the headers. Injecting them has never worked...

**Comment by axel-rank** [comment]
Hi,
I mean this small icon on the right that is showing up on external links.
HTML Links in Page Header like:
services:
    - header: Links
      text: a href="http://www.lefthandgear.de" target="_blank">Lefthandgear - Gitarren für Linkshänder</a>
I have a modular page, where I put these html links in header and those small link icons were shown until update to Grav 1.0.7

**Comment by Sommerregen** [comment]
Hi @axel-rank ,

I really doubt that this was working. I have never considered nor tested this. However how are you injecting those header links into the page? If you are using Twig you can render the links via `{{ page.content|external_links }}` in your Twig file (see https://github.com/Sommerregen/grav-plugin-external-links#twig-filter).

Otherwise as long as **External Links** is loaded and the respective CSS style, you can add the icon by adding the class `external` to the link (for reference see here https://github.com/Sommerregen/grav-plugin-external-links#css-stylesheet-override). In your case a link like

``` html
<a href="http://www.lefthandgear.de" target="_blank" class="external">
  Lefthandgear - Gitarren für Linkshänder
</a>
```

should be rendered with an external icon (even if you are injecting it via a page header).

**Comment by axel-rank** [comment]
Hi, I wouldn't have opened an issue, if it hasn't worked before GRAV 1.0.7
Don't hnow why you doubt, because I can use pure html (for links) in page header of .md files, as there are a lot templates who allow to insert text: ... in headers.
And those small icons for links generated were shown before Grav 1.0.7 without using class=external.
But thanks for the tip, now those fancy icons are here again.

**Comment by Sommerregen** [comment]
Hi @axel-rank I doubted for two reasons: (i) there are no obvious changes in the latest Grav versions, which could cause such behaviour and (ii) I never have tested this kind of config and couldn't have foreseen, that this was working before.

My doubt was not against you, it was a kind of misbelieving in the sense it shouldn't work, but as it seems I was wrong. I really don't know why it has worked for you, but glad to hear that the workaround works for you :-)
