### ISSUE TITLE
New release seems to have issue when upgrading Languages YAML

### ISSUE THREAD

**Issue by paulhibbitts** [Sommerregen/grav-plugin-external-links#18]
Hello,

Updating to the newest release today resulted in this error:

![2017-02-17_15-32-27](https://cloud.githubusercontent.com/assets/1812771/23087337/37ec07a6-f528-11e6-8ca9-4a70fe85d864.png)

Once I removed the plugin the error went away. Manually deleting and replacing the plugin with the newest release seems to cause the same error when in Admin.

Thanks for taking a look into this.
Paul

**Comment by jnncks** [comment]
I've just encountered the same error. The fix is quite simple since it's only two tiny mistakes in  **languages.yaml** which result in the file being malformed:
1. Line 183 should read `WWW_HELP: "Автоматически связывать любое имя хоста, которое начинается с 'www'. как внешние"`.
2.  Line 202 should read `MODE_ACTIVE: "Активный = обработка и разбор всех ссылок"`.

Edit: #17 already fixed it.

**Comment by Sommerregen** [comment]
Hi @paulhibbitts and @jnncks ,

sorry for any troubles ☹️ . I have merged #17 and released a new version. Next time I will check the code more carefully.

Thanks for all of you 👍
