### ISSUE TITLE
Possible issue with malformed URLs

### ISSUE THREAD

**Issue by paulhibbitts** [Sommerregen/grav-plugin-external-links#7]
After I had mistakenly formatted a URL without the 'http://' prefix (for example, [Grav](getgrav.org)) in a content page my site produced the following error:
![crikey there was an error](https://cloud.githubusercontent.com/assets/1812771/11194375/8cfa343e-8c60-11e5-95ed-4e30ddfe40de.png)

With some help I was able to locate the issue to the external_links plugin, and removing/disabling it fixed the error. I realize that the URL was malformed, but this might happen more than once and the resulting error in Grav is quite a show-stopper.

I am happy to try more tests, just let me know.

Thanks,
Paul

**Comment by Sommerregen** [comment]
Hi @paulhibbitts , yes I'm curious about this bug. Can you give me an example in quoted form (your's above seems a little broken, but do you mean `getgrav.org`)?

**Comment by paulhibbitts** [comment]
Hi Benny,

Yes, you are correct. Here is the commit that _I think_ triggered the issue (i.e. look for the cmpt-363 malformed link): https://github.com/hibbitts-design/hibbitts-design-org/commit/3fc3d0fef174f1d0dea821969a67c3f87543ba9d

Please let me know if you would like me to test anything, etc.

**Comment by Sommerregen** [comment]
Ok, thanks Paul. Interestingly I don't have this issue neither with `getgrav.org` nor with your commit. But anyhow from your tracetstack and the message I clearly see that's a bug in the plugin pointing me to right direction. More specifically https://github.com/Sommerregen/grav-plugin-external-links/blob/master/classes/ExternalLinks.php#L182 . I guess if you add

``` php
$colonpos = false;
```

before that line it will resolve your issue. But in order to make the external link recognition more stable there are more changes involved, than adding just one line. I will fix it (together with the title issue you informed me about some weeks ago) and hopefully have a new release today :smile: 

**UPDATE:** It turns out that changing [L200](https://github.com/Sommerregen/grav-plugin-external-links/blob/master/classes/ExternalLinks.php#L200) to

```
return $external;
```

yields the correct behaviour ;-)

**Comment by paulhibbitts** [comment]
Thanks for looking into the issue Benny, sounds like you've got a fix :-)
