### ISSUE TITLE
Image broken with CSS pipeline enabled

### ISSUE THREAD

**Issue by seb-vial** [Sommerregen/grav-plugin-external-links#9]
Hello there,
I'm not sure if I should post this issue here or if that's the case for every plugin that load images with relative paths in CSS. If I use the pipeline for CSS, I've got a 404 not found for the small external icon loaded from the CSS

![image_broken_404](https://cloud.githubusercontent.com/assets/5689193/11957574/d99efa6c-a8c2-11e5-9c45-0abe1c1a2ac3.jpeg)

![image_broken](https://cloud.githubusercontent.com/assets/5689193/11957540/a7a42dca-a8c2-11e5-88a8-36071d9c0b1b.jpeg)

**Comment by Sommerregen** [comment]
Hi @Birssan ,

IMHO this is a general problem, when pipelining CSS. A good parser who pipelines the code has to read all relative paths to images, fonts etc. from different CSS files and adjust them accordingly in the new pipelined CSS file.

Thus, this is either a **Grav** issue due to the code in [Assets.php, L1042 - L1068](https://github.com/getgrav/grav/blob/6e399fe0ed41937d5b71dc330c75e40bd53b2fbc/system/src/Grav/Common/Assets.php#L1042-L1068) or a [Minify issue](https://github.com/mrclay/minify).

You may try or check whether `assets.css_rewrite: true` is set to true (for reference: https://github.com/getgrav/grav/blob/6e399fe0ed41937d5b71dc330c75e40bd53b2fbc/system/config/system.yaml#L81). If the error persist, I recommend you opening an issue on the **Grav** issue tracker. Otherwise open an issue on the **Minify** project page.

**Comment by seb-vial** [comment]
Well yes I figured it was not because of the plugin, I should have checked that option first, sorry... I can't test it right now, I'll try that later. Thanks

**Comment by Sommerregen** [comment]
@Birssan Ok, no problem. Come back later, if there are any further issues.
